/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
import * as zod from "zod";

/**
 * Returns server health status
 * @summary Health check
 */
export const HealthCheckResponse = zod.object({
  status: zod.string(),
});

/**
 * Save a survey response
 * @summary Submit survey response
 */
export const SubmitSurveyBody = zod.object({
  mostImportantWord: zod.string(),
  mostImportantArea: zod.enum([
    "Family",
    "Friends",
    "School",
    "Career",
    "Health",
    "Money",
    "Personal Growth",
    "Faith",
  ]),
  careerImportance: zod.enum([
    "Very important",
    "Somewhat",
    "Neutral",
    "Slightly",
    "Not important",
  ]),
  meaningfulThings: zod.array(zod.string()),
  otherMeaningfulThing: zod.string().nullish(),
  whyItMatters: zod.string(),
});
