/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
export interface HealthStatus {
  status: string;
}

export type SurveySubmissionMostImportantArea =
  (typeof SurveySubmissionMostImportantArea)[keyof typeof SurveySubmissionMostImportantArea];

export const SurveySubmissionMostImportantArea = {
  Family: "Family",
  Friends: "Friends",
  School: "School",
  Career: "Career",
  Health: "Health",
  Money: "Money",
  Personal_Growth: "Personal Growth",
  Faith: "Faith",
} as const;

export type SurveySubmissionCareerImportance =
  (typeof SurveySubmissionCareerImportance)[keyof typeof SurveySubmissionCareerImportance];

export const SurveySubmissionCareerImportance = {
  Very_important: "Very important",
  Somewhat: "Somewhat",
  Neutral: "Neutral",
  Slightly: "Slightly",
  Not_important: "Not important",
} as const;

export interface SurveySubmission {
  mostImportantWord: string;
  mostImportantArea: SurveySubmissionMostImportantArea;
  careerImportance: SurveySubmissionCareerImportance;
  meaningfulThings: string[];
  /** @nullable */
  otherMeaningfulThing?: string | null;
  whyItMatters: string;
}

export interface SurveyResponse {
  id: number;
  mostImportantWord: string;
  mostImportantArea: string;
  careerImportance: string;
  meaningfulThings: string[];
  /** @nullable */
  otherMeaningfulThing?: string | null;
  whyItMatters: string;
  createdAt: string;
}

export interface ErrorResponse {
  error: string;
}
