/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
import type { SurveySubmissionCareerImportance } from "./surveySubmissionCareerImportance";
import type { SurveySubmissionMostImportantArea } from "./surveySubmissionMostImportantArea";

export interface SurveySubmission {
  mostImportantWord: string;
  mostImportantArea: SurveySubmissionMostImportantArea;
  careerImportance: SurveySubmissionCareerImportance;
  meaningfulThings: string[];
  /** @nullable */
  otherMeaningfulThing?: string | null;
  whyItMatters: string;
}
